# Configuración de logging
logging:
  version: 1

  formatters:
    standard:
        datefmt: "%d-%m-%Y %H:%M:%S"
        format: "%(asctime)s %(levelname)s: %(name)s::%(funcName)s -> (linea %(lineno)d) %(message)s"

  handlers:
    console: 
      level: WARNING
      class: logging.StreamHandler
      formatter: standard
      stream: ext://sys.stdout

    file:
      class: logging.FileHandler
      level: INFO
      formatter: standard
      filename: 'app.log'
      
  root:
    level: INFO
    handlers:
      - console
      - file
    