# Ultima versión del motor de procesamiento de canalización CircleCI
# En caso de nueva versión actualizar
version: 2.1

# Los Orbs son paquetes reutilizables de configuración de CircleCI que puede compartir entre proyectos.
orbs:
  python: circleci/python@1.2

# Define a job to be invoked later in a workflow.
jobs:
  build-and-test: # Nombre del Job
    docker:
      - image: antobio17/iv:latest
        environment:
          DATEFORMAT_LOG: DATEFORMAT_LOG
          FORMAT_LOG: FORMAT_LOG
          LEVEL_CONSOLE_LOG: LEVEL_CONSOLE_LOG
          LEVEL_FILE_LOG: LEVEL_FILE_LOG
          FILENAME_FILE_LOG: FILENAME_FILE_LOG
    steps:
      - checkout
      - run:
          name: Run tests
          command: invoke test

# Lanzar jobs a través de workflows
workflows:
  sample: # Nombre del workflow
    jobs:
      - build-and-test