name: Check config

on:
  push:
    paths:
      - 'config.yml'
      - '.gitignore'
      - '.github/workflows/config_checker.yml'
      - '.github/workflows/gitignore_checker.sh'
    branches:
      - '*'
    

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      name: Checkout del repositorio 

    - name: Comprobar que config.yml está añadido al gitignore
      id: check_gitignore
      run: echo "::set-output name=result::$(sh ./.github/workflows/gitignore_checker.sh)"

    - name: Chek config.yml en .gitignore 
      if: steps.check_gitignore.outputs.result != 'true'
      uses: actions/github-script@v3
      with:
        script: |
          core.setFailed('❌ El fichero config.yml no está añadido en el .gitignore')

    - name: Check file existence
      id: check_file
      uses: andstor/file-existence-action@v1
      with:
        files: ".env"

    - name: Existe dotenv
      if: steps.check_file.outputs.files_exists == 'true'
      uses: actions/github-script@v3
      with:
        script: |
          core.setFailed('❌ El fichero config.yml no puede añadirse al repositorio remoto!!')
