name: Dockerhub

on:
  push:
    paths:
      - 'Dockerfile'
    branches:
      - '*'

jobs:
  push_to_registry:
    name: Push imagen de Docker a DockerHub
    runs-on: ubuntu-latest
    steps:
      - name: Descarga de los fuentes del repositorio
        uses: actions/checkout@v2

      - name: Inicio de sesión en DockerHub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build y push de la imagen Docker
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: true
          tags: antobio17/iv:latest